on:
  pull_request:
  push:
    branches:
      - main
jobs:
  setup-role-and-get-caller-identity:
    name: Setup role and get caller identity
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: "./"
        with:
          aws-role-arn: arn:aws:iam::123456789012:role/assume-role
      - run: apt install -y awscli2
      - run: aws sts get-caller-identity
